### ISSUE TITLE
Doctrine destination

### ISSUE THREAD

**Issue by rvmourik** [DivineOmega/uxdm#10]
So it can be used with Symfony

**Comment by DivineOmega** [comment]
Started work on this in the https://github.com/DivineOmega/uxdm/tree/doctrine branch.

**Comment by rvmourik** [comment]
Very good!

**Comment by rvmourik** [comment]
@DivineOmega don't have enough time to clone the project and check the code, but i reviewed it quickly and it does look good. I've added a comment at one of the commits.

Also is see you make us of doctrine/orm 2.5.x, is there a reason why you're not using 2.6?

**Comment by DivineOmega** [comment]
@rvmourik Thanks for the feedback.

I'll consider the property access package you commented about here: https://github.com/DivineOmega/uxdm/commit/9ebef9177fcb69223bd70e6c067b7e62cc9ceee2#r29179392. Looks pretty useful.

You're right, I should be using 2.6. There was no good reason for using 2.5. I'll up the minimum version number as well.

**Comment by DivineOmega** [comment]
This is now using Doctrine ORM 2.6 and the `symfony/property-access` package to call the setter methods.
