### ISSUE TITLE
Split certain source and destinations into seperate packages (?)

### ISSUE THREAD

**Issue by DivineOmega** [DivineOmega/uxdm#12]
Some packages, such as the Eloquent source/destination and the upcoming Doctrine destination bring in non-trivial dependencies. It might be worth splitting these sources out into their own `uxdm-eloquent` and `uxdm-doctrine` packages.

**Comment by mrbig00** [comment]
I think that also removing the progress bar dependency would be a good idea

**Comment by DivineOmega** [comment]
This issue is now resolved as of [v3.0.0](https://github.com/DivineOmega/uxdm/releases/tag/v3.0.0).

**Comment by DivineOmega** [comment]
@mrbig00 v3.0.0 does not remove the progress bar dependency as I believe that is a different concern. If you'd like to discuss this, feel free to open a new issue.
