### ISSUE TITLE
Broken XML source pagination

### ISSUE THREAD

**Issue by mrbig00** [DivineOmega/uxdm#33]
If I load large XML file, for example with 5000 items, only every tenth of the item is present:

**How to reproduce**

Load any kind of XML with a few hundred elements and use it:

```php
$source = new XmlSource('input.xml', '/items/product');
$destination = new CsvDestination();
$this->migrator
     ->setDataItemManipulator($this->getDataItemManipulator())
     ->setSource($source)
     ->setDestination($destination)
     ->setKeyFields(['id'])
     ->withProgressBar()
     ->migrate();
```
**Note**
the total number of items counts good

**Comment by DivineOmega** [comment]
Thanks for the bug report. Unfortunately, I can't seem to replicate this.

Would you be able to provide the `input.xml` you are using?

Also, is the problem present if you use a different destination?

**Comment by mrbig00** [comment]
Oh, shoot.

My bad! It was a return in the `putDataRows` method. 

So the issue is invalid :)

**Comment by DivineOmega** [comment]
Glad you got it resolved.

Were you using a custom `CsvDestination` then? If so, could I ask why? UXDM does come with a CSV destination built in.

**Comment by mrbig00** [comment]
Nope, the CsvDestination is just for the demo purposes :) I was using a custom destintatnion
